### PR TITLE
Fix conflict with classic schema, related to my issue (needs test)

### PR DESCRIPTION
**Pull request by hikariatama**
All I've done - just removed the occurrences of telethon schema entities from secret_schema. This is related to my issue https://github.com/painor/telethon-secret-chat/issues/11
Also, I tested it with the environment, mentioned in issue, and wanted functions work ok.

Btw, the folder with schema is named `secret_sechma` 👍

### CODE REVIEW

**Comment by hikariatama** [comment]
Btw, I didn't expect that if I just remove conflicting entities, it'll still work. Ig, it'll be better, if other conflicting lines are removed, but I'm too lazy to check 'em 😅

**Comment by painor** [comment]
why didn't you just delete them instead of adding a # at the start, it makes them look a bit messy

**Comment by hikariatama** [comment]
> why didn't you just delete them instead of adding a # at the start, it makes them look a bit messy 

Yeee, I'm just a bit of dumb in programming, and always comment lines instead of removing, if they are meaningful))

**Comment by painor** [comment]
well feel free to remove them so I can approve this and merge

**Comment by hikariatama** [comment]
K, I removed them after a break. Also, Sourcery plugin suggested some fixes, mostly with ternary operator, so I agreed with him 😌

**Pull request merged**
